################## Application Configuration - Local ####################
---
spring:
  config:
    activate:
      on-profile: peer-1
    import: "optional:configserver:http://localhost:8091"
  cloud:
    config:
      name: peer-1,cloud-bus
      profile: local

server:
  port: ${PORT:3001}
---
spring:
  config:
    activate:
      on-profile: peer-2
    import: "optional:configserver:http://localhost:8091"
  cloud:
    config:
      name: peer-2,cloud-bus
      profile: local

server:
  port: ${PORT:3002}
---
spring:
  config:
    activate:
      on-profile: peer-3
    import: "optional:configserver:http://localhost:8091"
  cloud:
    config:
      name: peer-3,cloud-bus
      profile: local

server:
  port: ${PORT:3003}


################## Application Configuration - Docker ####################
---
spring:
  config:
    activate:
      on-profile: peer-docker-1
    import: "optional:configserver:http://config-server:8091"
  cloud:
    config:
      name: peer-1,cloud-bus
      profile: docker

server:
  port: ${PORT:3001}
---
spring:
  config:
    activate:
      on-profile: peer-docker-2
    import: "optional:configserver:http://config-server:8091"
  cloud:
    config:
      name: peer-2,cloud-bus
      profile: docker

server:
  port: ${PORT:3002}
---
spring:
  config:
    activate:
      on-profile: peer-docker-3
    import: "optional:configserver:http://config-server:8091"
  cloud:
    config:
      name: peer-3,cloud-bus
      profile: docker

server:
  port: ${PORT:3003}