################## Eureka Configuration ####################
---
spring:
  config:
    activate:
      on-profile: peer-1
  application:
    name: EUREKA-SERVER-CLUSTERED
server:
  port: 3001
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:3002/eureka/, http://localhost:3003/eureka/
  server:
    response-cache-update-interval-ms: 1000

---
spring:
  config:
    activate:
      on-profile: peer-2
  application:
    name: EUREKA-SERVER-CLUSTERED
server:
  port: 3002
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/, http://localhost:3003/eureka/
  server:
    response-cache-update-interval-ms: 1000

---
spring:
  config:
    activate:
      on-profile: peer-3
  application:
    name: EUREKA-SERVER-CLUSTERED
server:
  port: 3003
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/, http://localhost:3002/eureka/
  server:
    response-cache-update-interval-ms: 1000
