################## Application Settings ####################
spring:
  application:
    name: Eureka Server

server:
  port: ${PORT:8080}

################## Eureka Configuration ####################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: true


